version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "9000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    pgdata:
